# Site settings
title: TSmithPhotos
email: your-email@domain.com
description: 
baseurl: ""
url: "http://www.tsmithphotos.com" # the base hostname & protocol for your site
twitter_username: tsmith512
github_username:  tsmith512

# Build settings
markdown: kramdown

exclude:
  - source # Don't include the original photos directory

keep_files:
  - photo # Don't clobber the photo exports directory

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
